version: '3.9'

networks:
  default:
    driver: bridge

volumes:
  db:

services:
  nginx:
    image: nginx
    ports: [80:80]
    volumes:
      - ./:/var/www
      - ./.docker/nginx/server.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql:8.4
    ports: [3306:3306]
    volumes:
      - db:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypass
      - MYSQL_ROOT_PASSWORD=rpass

  app: &app
    build:
      dockerfile: dockerfile
    working_dir: /var/www/
    volumes: [./:/var/www]
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=servitor
      - DB_USERNAME=myuser
      - DB_PASSWORD=mypass
