@startuml Покупка подписки
actor Клиент as client
participant Приложение as app
participant "YooKassa SDS" as sdk
participant api
participant ЮKassa as kassa

activate app
client -> app: Оформить подписку
app -> api: POST /order {period}
activate api
app <- api: Order: {sum: 300, content: 12 monthes}
app -> sdk: startTokenize
app <- sdk: token
app -> api: POST /order/_id/payment {token}
api -> kassa: POST /payments
api <- kassa: {id}
app <- api: Payment: {sum, confirmation_url}
app -> sdk: {confirmation_url}
client <- sdk: Подтверждение оплаты
client -> sdk: Подтверждение платежа
app <- sdk: paid
app -> api: POST /payment/_id/check
api -> kassa: GET /payments/_id
api <- kassa: {payment}
app <-- api: {success}
deactivate api
client <-- app: {success}
deactivate app
@enduml
