name: Deploy to Production

on: workflow_dispatch

permissions:
  contents: read

jobs:
  deploy:
    environment: beget

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup environment
      run: |
        echo APP_KEY=${{ secrets.APP_KEY }} >> .env
        echo APP_URL=${{ vars.APP_URL }} >> .env
        echo DB_CONNECTION=${{ $vars.DB_CONNECTION }} >> .env
        echo DB_DATABASE=${{ vars.DB_DATABASE }} >> .env
        echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env
        echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env

    - name: Upload
      uses: Dylan700/sftp-upload-action@latest
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        uploads: |
          app => ./
          bootstrap => ./
          config => ./
          database => ./
          public => ./
          resources => ./
          routes => ./
          storage => ./
          .env => ./
          composer.json => ./
          composer.lock => ./
